# Generated by Django 5.2.10 on 2026-01-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('MAIS', 'Maïs'), ('SOJA', 'Soja'), ('ANANAS', 'Ananas')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Type de Culture',
                'verbose_name_plural': 'Types de Cultures',
            },
        ),
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, help_text='Quantité en kg', max_digits=10)),
                ('date_recolte', models.DateField()),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('observations', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recoltes/')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoltes', to='producteurs.parcelle')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoltes', to='producteurs.producteur')),
                ('type_culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoltes.typeculture')),
            ],
            options={
                'verbose_name': 'Récolte',
                'verbose_name_plural': 'Récoltes',
                'ordering': ['-date_recolte'],
            },
        ),
    ]
