# Generated by Django 5.2.10 on 2026-01-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producteurs', '0001_initial'),
        ('recoltes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacite_max', models.DecimalField(decimal_places=2, help_text='Capacité maximale en kg', max_digits=10)),
                ('adresse', models.CharField(max_length=255)),
                ('gestionnaire', models.CharField(max_length=100)),
                ('telephone_gestionnaire', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='entrepots/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('arrondissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepots', to='producteurs.arrondissement')),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_actuelle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, help_text="Seuil d'alerte en kg", max_digits=10)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stockage.entrepot')),
                ('type_culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoltes.typeculture')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'unique_together': {('entrepot', 'type_culture')},
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('motif', models.CharField(max_length=255)),
                ('operateur', models.CharField(blank=True, max_length=100)),
                ('recolte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recoltes.recolte')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stockage.stock')),
            ],
            options={
                'verbose_name': 'Mouvement de Stock',
                'verbose_name_plural': 'Mouvements de Stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
