# Generated by Django 5.2.10 on 2026-01-22 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockage', '0002_migrate_gestionnaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepot',
            name='gestionnaire',
            field=models.ForeignKey(blank=True, help_text='Gestionnaire responsable de cet entrepôt', limit_choices_to={'groups__name': 'Gestionnaires'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
