# Generated by Django 5.2.10 on 2026-01-19 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
            },
        ),
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrondissements', to='producteurs.commune')),
            ],
            options={
                'verbose_name': 'Arrondissement',
                'verbose_name_plural': 'Arrondissements',
            },
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='producteurs/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('arrondissement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producteurs.arrondissement')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producteur',
                'verbose_name_plural': 'Producteurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='Superficie en hectares', max_digits=10)),
                ('localisation', models.CharField(help_text='Description de la localisation', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parcelles/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='producteurs.producteur')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
            },
        ),
    ]
